### ISSUE TITLE
error on djcopyright.context_processors.djcopyright_years

### ISSUE THREAD

**Issue by SoulRaven** [vint21h/django-djcopyright#2]
normally the req param must be on 
def djcopyright_years(req):
not
def djcopyright_years():

if the param is not there, django throws error

**Comment by vint21h** [comment]
Thanks! Try new version.

**Comment by SoulRaven** [comment]
is on pip, or from repository

**Comment by vint21h** [comment]
Version 0.2.3 uploaded to PyPI.
